name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          set-safe-directory: true
      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y meson ninja-build glslang-dev glslang-tools libvulkan-dev vulkan-tools libstb-dev libsdl2-dev
      - run: |
          meson setup build
          cd build
          ninja
      - run: |
          export REL_NAME="release-$(date +%Y%m%d%H%M%S)"
          gh release create $REL_NAME -t "${REL_NAME}" --generate-notes build/robbit
