name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
      name: Meson Build
  # You may pin to the exact commit or the version.
  # uses: BSFishy/meson-build@656b2a360964b249ac82905a52018921e01d875b
      uses: BSFishy/meson-build@v1.0.3
